- name: "demo_ppl"
  timeout: 10
  path: "nodes"
  nodes:
    - name: "node_a"
      path: "nodes.node_a"
      class_name: "NodeA"
      enabled: True
      required: True
      timeout: 3
      next_nodes:
        - "node_b"
        - "node_c"
    
    - name: "node_b"
      path: "nodes.node_b"
      class_name: "NodeB"
      enabled: True
      required: True
      timeout: 3
      next_nodes:
        - "node_d"
    
    - name: "node_c"
      path: "nodes.node_c"
      class_name: "NodeC"
      enabled: True
      required: True
      timeout: 3
      next_nodes:
        - "node_d"

    - name: "node_d"
      path: "nodes.node_d"
      class_name: "NodeD"
      enabled: True
      required: True
      timeout: 3
      next_nodes:
    
    
      
